general:
  # Options: bunker (destroy), vanish (scrub), lockdown (freeze)
  default_mode: "bunker" 
  watchdog_timeout: 300
  safe_password: "LiveFreeOrDie"
  duress_password: "password123"

system:
  # SAFE TEST TARGET (pointing to your dummy file for now!)
  self_destruct_target: "/home/sanchay-jain/Desktop/dummy_drive.img" 
  network_interface: "enp0s3"

modes:
  vanish:
    # Files/Directories to securely shred before vanishing
    target_paths:
       - "/tmp/scram_dummy_*"
    #  - "/var/log/syslog"
    #  - "/var/log/auth.log"
    #  - "/home/*/.bash_history"
    #  - "/tmp/*"
  modes:
  canary:
    enabled: true
    filepath: "/home/sanchay-jain/Desktop/Crypto_Wallets.txt" #change to your desired as well as in canary.py
    
  usb_sentry:
    enabled: true
    whitelist:
      - "ID"  # Replace with USB ID from lsusb